"""
    struct LIME{M} <: AbstractXAIMethod

The `LIME` (Local Interpretable Model-agnostic Explanations) struct is used to create an instance of the LIME method for explainable AI (XAI). This method provides local explanations for the predictions of any machine learning model by approximating the model's behavior in the vicinity of a specific input.

# Fields
- `model::M`: The machine learning model to be explained. The model should be callable with an input to produce an output.
"""

struct LIME{M, K, l} <: AbstractXAIMethod 
    model::M
    kernel::K
    lasso::l

end

LIME(M) = LIME(M, exponential_kernel, true)

#implementation of LIME XAI method based on https://arxiv.org/pdf/1602.04938
"""
    (method::LIME)(input, output_selector::AbstractOutputSelector)

This function applies the LIME (Local Interpretable Model-agnostic Explanations) method to a given input and returns an explanation of the model's prediction.

# Arguments
- `input`: The input data for the model, typically a 4D array (e.g., image data with dimensions height x width x channels x batch size).
- `output_selector::AbstractOutputSelector`: An object that selects specific outputs from the model's predictions.

# Returns
- `Explanation`: An object containing the following fields:
    - `val`: The explanation value generated by the `explain_instance` function.
    - `output`: The output of the model for the given input.
    - `output_selection[1]`: The selected output used for generating the explanation.
    - `:MyMethod`: The method used for generating the explanation.
    - `:attribution`: The type of explanation provided (attribution).
    - `extras`: Additional information related to the explanation (currently set to `nothing`).
"""
function (method::LIME)(input, output_selector::AbstractOutputSelector)
    output = method.model(input)
    output_selection = output_selector(output)

    #select first input
    input = input[:,:,:,1]

    val = explain_instance(input, method.model, output_selection[1]; kernel=method.kernel, lasso=method.lasso)
    extras = nothing
    return Explanation(val, output, output_selection[1], :MyMethod, :attribution, extras)
end

